### ISSUE TITLE
The website doesn't work

### ISSUE THREAD

**Issue by Aymkdn** [alexander-ruehle/paper-collapse#10]
Hi,

I'm trying the link http://bbo-code.com/components/paper-collapse and it returns an error : 
```
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.
```

**Comment by alexander-ruehle** [comment]
Hi,
thank you for your feedback.
I think that your chinese locale chrashed the site.

Please try again.

**Comment by Aymkdn** [comment]
It's back ! Thanks
